In [1]:
import numpy as np
import pandas as pd
from DecisionTreeClassifier import DecisionTreeClassifier

In [2]:
data = pd.read_csv('diabetes.csv')

In [3]:
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
clasf = DecisionTreeClassifier(data=data, y_col='Outcome', max_depth=6)

In [6]:
clasf.fit()

In [12]:
nodes = [clasf.head]
while len(nodes) > 0:
    cur_node = nodes[0]
    del nodes[0]
    if cur_node.split_val is not None:
        print(cur_node.split_col + ': ' + str(cur_node.split_val))
    if cur_node.left is not None:
        nodes.append(cur_node.left)
    if cur_node.right is not None:
        nodes.append(cur_node.right)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
1,1,85,66,29,0,26.6,0.351,31,0
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
6,3,78,50,32,88,31.0,0.248,26,1
8,2,197,70,45,543,30.5,0.158,53,1
...,...,...,...,...,...,...,...,...,...
758,1,106,76,0,0,37.5,0.197,26,0
760,2,88,58,26,16,28.4,0.766,22,0
764,2,122,70,27,0,36.8,0.340,27,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [14]:
print(clasf.head.left.left.left.split_col)

Age

In [7]:
1 - (0.34234234234234234**2 + 0.6576576576576576**2)

0.45028812596380163